# NumPy 入门

## 1. array基本属性

In [14]:
import numpy as np
arr1 = np.array([6, 2, -7, 2, 8, -2, 1])
arr2 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr1)
arr2

[ 6  2 -7  2  8 -2  1]


array([[1, 3, 5],
       [2, 4, 6]])

In [10]:
print(arr1.ndim, arr1.shape, arr1.size, arr1.dtype )
print(arr2.ndim, arr2.shape, arr2.size, arr2.dtype )

1 (7,) 7 int32
2 (2, 3) 6 int32


In [13]:
arr_all_zero = np.zeros(6)
arr_all_one = np.ones(6) # 浮点
print(arr_all_zero, "\n", arr_all_one)

[0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1.]


In [12]:
arr_arange = np.arange(10, 21, 2)
arr_arange

array([10, 12, 14, 16, 18, 20])

 ## 2. Array Methods

In [20]:
import numpy as np

arr1 = np.array([6, 2, -7, 2, 8, -2, 1])
arr2 = np.zeros(2)

arr = np.concatenate([arr1, arr2]) # np.concatenate([arr1, arr2, ···])
arr

array([ 6.,  2., -7.,  2.,  8., -2.,  1.,  0.,  0.,  1.,  1.])

In [19]:
# np.sort(array)
print(np.sort(arr)) # 排序arr并返回， 不改变arr
# arr.sort()
print(arr.sort()) # 不返回， arr被改变
arr

[-7. -2.  0.  0.  1.  2.  2.  6.  8.]
None


array([-7., -2.,  0.,  0.,  1.,  2.,  2.,  6.,  8.])

In [21]:
# max, min, sum, mean,std
print(arr.max(), arr.min(), arr.sum(), arr.mean(), arr.std() )

8.0 -7.0 12.0 1.0909090909090908 3.703917961356974


In [14]:
# 根据条件筛选元素
arr = np.sort(np.array([-7., -2.,  0.,  0.,  1.,  2.,  2.,  6.,  8.]) )
new_arr = arr > 6 # bool array
print(new_arr)
print(arr[arr > 6])
print(arr[(arr < 1) | (arr > 3)]) # 必须括号


[False False False False False False False False  True]
[8.]
[-7. -2.  0.  0.  6.  8.]


In [10]:
import numpy as np

arr1 = np.array([1, 3, 2, 4, 9])
arr2 = np.ones(5)
arr3 = np.zeros(3)

arr4 = np.concatenate([arr1, arr2, arr3]) 
arr4

arr1.sort()
arr1[-3]
print(arr1[1:4])

print(arr1 + arr2)
arr1.max()

[2 3 4]
[ 2.  3.  4.  5. 10.]


9

In [ ]:
import numpy as np

# 1）从 Python 列表/元组创建
a = np.array([1, 2, 3])                 # 1‑D 向量
b = np.array([[1, 2], [3, 4]])          # 2‑D 矩阵

# 2）等差、等距序列
c = np.arange(0, 10, 2)                 # [0 2 4 6 8]
d = np.linspace(0, 1, 5)                # [0.   0.25 0.5  0.75 1.  ]

# 3）全 0、全 1、常数矩阵
z = np.zeros((3, 4))                    # 3×4 全 0
o = np.ones((2, 5))                     # 2×5 全 1
k = np.full((2, 3), 7)                  # 填充常数 7

# 4）单位矩阵、对角矩阵
I = np.eye(4)                           # 4×4 单位矩阵
D = np.diag([1, 2, 3])                  # 对角矩阵

# 常用的数组操作 与 向量化计算

## 创建数组

In [1]:
import numpy as np

# 1）从 Python 列表/元组创建
a = np.array([1, 2, 3])                 # 1‑D 向量
b = np.array([[1, 2], [3, 4]])          # 2‑D 矩阵

# 2）等差、等距序列
c = np.arange(0, 10, 2)                 # [0 2 4 6 8]
d = np.linspace(0, 1, 5)                # [0.   0.25 0.5  0.75 1.  ]

# 3）全 0、全 1、常数矩阵
z = np.zeros((3, 4))                    # 3×4 全 0
o = np.ones((2, 5))                     # 2×5 全 1
k = np.full((2, 3), 7)                  # 填充常数 7

# 4）单位矩阵、对角矩阵
I = np.eye(4)                           # 4×4 单位矩阵
D = np.diag([1, 2, 3])                  # 对角矩阵

In [2]:
D 

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## 索引、切片、布尔掩码

x = np.arange(10)          # [0 1 2 3 4 5 6 7 8 9]

# 1）单个元素
x[3]            # 3
x[-1]           # 9

# 2）切片
x[2:8]          # [2 3 4 5 6 7]
x[:5]           # 前 5 个
x[5:]           # 从第 6 个到结束
x[::2]          # 步长为 2 的子序列

# 3）二维切片
M = np.arange(1, 13).reshape(3, 4)
M[0, 2]         # 第 1 行第 3 列 → 3
M[1:, :2]       # 取第 2、3 行的前两列

# 4）布尔掩码
mask = x > 5
x[mask]         # [6 7 8 9]

# 5）花式索引（整数数组索引）
indices = np.array([0, 2, 4, 6])
x[indices]      # [0 2 4 6]

## 基本算术（逐元素

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A + B            # [5 7 9]
A - 2            # [-1  0  1]
A * B            # [4 10 18]
A / B            # [0.25 0.4  0.5 ]
A ** 2           # [1 4 9]
np.sqrt(A)       # [1.         1.41421356 1.73205081]
np.log(A)        # [0.         0.69314718 1.09861229]

## 广播（Broadcasting）

In [ ]:
# 1）向量与标量
v = np.arange(4)          # [0 1 2 3]
v + 10                    # [10 11 12 13]

# 2）不同形状的矩阵相加（自动扩展）
col = np.arange(3).reshape(3, 1)   # 3×1 列向量
row = np.arange(4)                 # 1×4 行向量
C = col + row                      # 结果 3×4 矩阵
# [[0 1 2 3]
#  [1 2 3 4]
#  [2 3 4 5]]

## 通用函数

In [ ]:
t = np.linspace(0, 2*np.pi, 6)
np.sin(t)            # 正弦
np.exp(t)            # 指数
np.abs([-3, -1, 2])  # 绝对值
np.maximum(A, B)     # 对应元素取较大值
np.minimum(A, B)     # 对应元素取较小值

##  归约（Reduction）操作

In [ ]:
M = np.arange(1, 13).reshape(3, 4)

M.sum()                 # 所有元素之和 → 78
M.mean()                # 均值 → 6.5
M.std(ddof=0)           # 标准差（总体） → 3.605551275
M.var(ddof=1)           # 方差（样本） → 13.0

# 按轴（axis）归约
M.sum(axis=0)           # 按列求和 → [12 15 18 21]
M.mean(axis=1)          # 按行求均值 → [2.5 6.5 10.5]
M.max()                 # 最大值 → 12
M.argmin()              # 扁平化后最小值索引 → 0
M.argmax(axis=1)        # 每行最大值所在列索引 → [3 3 3]

## 线性代数(np.linalg)

In [ ]:
A = np.array([[2, 1],
              [1, 3]])

# 矩阵乘法
B = np.array([[1, 0],
              [0, 1]])
A @ B                     # 同 np.dot(A, B)

# 转置
A.T

# 逆矩阵
np.linalg.inv(A)

# 解线性方程组 A·x = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)

# 特征值、特征向量
w, v = np.linalg.eig(A)   # w 为特征值，v 为对应特征向量（列向量）

# 奇异值分解
U, s, VT = np.linalg.svd(A)   # s 为奇异值向量

## 随机数(np.random)

In [ ]:
# 1）均匀分布
u = np.random.rand(3, 2)          # 形状 (3,2) 的浮点数，范围 [0,1)

# 2）正态分布
n = np.random.randn(5)            # 标准正态（均值0，方差1）

# 3）整数随机抽样
ints = np.random.randint(0, 10, size=(2, 3))   # 2×3 矩阵，取值 0~9

# 4）随机排列（shuffle）
arr = np.arange(10)
np.random.shuffle(arr)           # 原地打乱顺序

## 常用的 reshape / 转置 / 视图操作

In [ ]:
x = np.arange(12)

# reshape（返回原array指针，不复制数据）
x2 = x.reshape((3, 4))           # 3×4 矩阵

# ravel（扁平化为 1‑D，返回原array指针）
x3 = x2.ravel()                  # 与 x 本质相同
# flatten（返回拷贝）
x4 = x2.flatten()                # 新的 1‑D 数组

# 转置
x2.T                          